var dataUrl = 'data/RF_2014_Anonym.txt';
var maxZoom = 18;
var fieldSeparator = '\t';
//var baseUrl = 'http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png';
var baseUrl = '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
var baseAttribution= 'Karte &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>. Lieznz <a href="http://opendatacommons.org/licenses/odbl/">ODbL</a>';
var subdomains = 'abc';
var clusterOptions = {showCoverageOnHover: false, maxClusterRadius: 50};
var labelColumn = "Name";
var opacity = 1.0;